{% set name = "pycoxmunk" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycoxmunk-{{ version }}.tar.gz
  sha256: 8860d47c5bb0e8524e646d65a64527bc60cda27158efe083708a2a4ef4c1a41f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.2
    - scipy >=1.7.1
    - pandas >=1.3.4
    - dask-core >=2021.10.0
    - pyorbital >=1.7.1
    - pyresample >=1.22.1
    - satpy >=0.30
    - click >=8.0.3
    - numba >=0.55.0
    - xarray >=0.20.2

test:
  imports:
    - pycoxmunk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simonrp84/PyCoxMunk
  summary: An algorithm to compute sea surface reflectance using the Cox-Munk approach.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - simonrp84
